### ISSUE TITLE
Not working on Windows7

### ISSUE THREAD

**Issue by TeachMeJavaTonight** [nettitude/RunPE#6]
```
[*] Patching kernelbase!GetModuleHandleW to return base address of loaded PE if
called with NULL
[*] Calculating patch length for kernelbase!GetModuleHandleW
[-] Error running RunPE: System.Exception: Unable to calculate patch length, the
 function may have changed to a point it is is no longer recognised and this cod
e needs to be updated
   at RunPE.Patchers.ExtraAPIPatcher.CalculatePatchLength(IntPtr funcAddress)
   at RunPE.Patchers.ExtraAPIPatcher.PatchAPIs(IntPtr baseAddress)
   at RunPE.Program.Main(String[] args)
```

**Comment by m0rv4i** [comment]
Thanks but given Win7 is end of life we won't be supporting it, however if you'd like to add it you can add a new search pattern here: https://github.com/nettitude/RunPE/blob/main/RunPE/Patchers/ExtraAPIPatcher.cs#L133 for the specific version you're on with the appropriate length (which just has to be the length in bytes of a complete set of instructions).
